# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: git submodule init && git submodule update && yarn
    command: yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - description: Vite hot reload
    port: 3000
    onOpen: ignore
    visibility: public

  - description: Wranger service registry
    port: 6284
    onOpen: ignore

  - description: Inspector
    port: 9229
    onOpen: ignore

  - description: Miniflare public
    port: 8788
    onOpen: notify
    visibility: public
